CREATE TABLE `users` (
  `id` varchar(191) COLLATE utf8mb4_bin NOT NULL,
  `fullName` longtext COLLATE utf8mb4_bin,
  `email` longtext COLLATE utf8mb4_bin,
  `anonymous` longtext COLLATE utf8mb4_bin,
  `phoneNumber` longtext COLLATE utf8mb4_bin,
  `phoneCountryCode` longtext COLLATE utf8mb4_bin,
  `password` longtext COLLATE utf8mb4_bin,
  `googleEmail` longtext COLLATE utf8mb4_bin,
  `authProvider` longtext COLLATE utf8mb4_bin,
  `sessionId` longtext COLLATE utf8mb4_bin,
  `walletCreditPaymentIds` longtext COLLATE utf8mb4_bin,
  `age` double DEFAULT NULL,
  `gender` longtext COLLATE utf8mb4_bin,
  `role` longtext COLLATE utf8mb4_bin,
  `profileCompleted` tinyint(1) DEFAULT NULL,
  `chatContext` longtext COLLATE utf8mb4_bin,
  `isEmailVerified` tinyint(1) DEFAULT NULL,
  `isPhoneVerified` tinyint(1) DEFAULT NULL,
  `dateOfBirth` datetime(3) DEFAULT NULL,
  `bloodGroup` longtext COLLATE utf8mb4_bin,
  `address` longtext COLLATE utf8mb4_bin,
  `emergencyContact` longtext COLLATE utf8mb4_bin,
  `medicalInfo` longtext COLLATE utf8mb4_bin,
  `insuranceInfo` longtext COLLATE utf8mb4_bin,
  `specialization` longtext COLLATE utf8mb4_bin,
  `consultationMode` longtext COLLATE utf8mb4_bin,
  `languages` longtext COLLATE utf8mb4_bin,
  `education` longtext COLLATE utf8mb4_bin,
  `rating` double DEFAULT NULL,
  `ratingCount` double DEFAULT NULL,
  `totalSessions` double DEFAULT NULL,
  `activeClients` double DEFAULT NULL,
  `profilePhotoPublicId` longtext COLLATE utf8mb4_bin,
  `chatPermission` longtext COLLATE utf8mb4_bin,
  `isActive` tinyint(1) DEFAULT NULL,
  `isVerified` tinyint(1) DEFAULT NULL,
  `isOnline` tinyint(1) DEFAULT NULL,
  `lastSeen` datetime(3) DEFAULT NULL,
  `walletBalance` double DEFAULT NULL,
  `devicePlatform` longtext COLLATE utf8mb4_bin,
  `instantPayoutCount` double DEFAULT NULL,
  `payoutAccount` longtext COLLATE utf8mb4_bin,
  `locationConsent` tinyint(1) DEFAULT NULL,
  `locationData` longtext COLLATE utf8mb4_bin,
  `certifications` longtext COLLATE utf8mb4_bin,
  `createdAt` datetime(3) DEFAULT NULL,
  `updatedAt` datetime(3) DEFAULT NULL,
  `__v` double DEFAULT NULL,
  `googleId` longtext COLLATE utf8mb4_bin,
  `activeWalletRefundRequest` tinyint(1) DEFAULT NULL,
  `prescriptionSeal` longtext COLLATE utf8mb4_bin,
  `prescriptionSignature` longtext COLLATE utf8mb4_bin,
  `lastActiveAt` datetime(3) DEFAULT NULL,
  `fcmToken` longtext COLLATE utf8mb4_bin,
  `walletAdjustmentIds` longtext COLLATE utf8mb4_bin,
  `phone` longtext COLLATE utf8mb4_bin,
  `profilePicture` longtext COLLATE utf8mb4_bin,
  `hourlyRate` double DEFAULT NULL,
  `sessionsDone` double DEFAULT NULL,
  `bio` longtext COLLATE utf8mb4_bin,
  `availability` longtext COLLATE utf8mb4_bin,
  `emailOTP` longtext COLLATE utf8mb4_bin,
  `phoneOTP` longtext COLLATE utf8mb4_bin,
  `qualification` longtext COLLATE utf8mb4_bin,
  `experience` double DEFAULT NULL,
  `location` longtext COLLATE utf8mb4_bin,
  `aboutMe` longtext COLLATE utf8mb4_bin,
  `uniqueCode` longtext COLLATE utf8mb4_bin,
  `profilePhoto` longtext COLLATE utf8mb4_bin,
  `refreshToken` longtext COLLATE utf8mb4_bin,
  `accountType` longtext COLLATE utf8mb4_bin,
  `doctorQrCode` longtext COLLATE utf8mb4_bin,
  `staffId` longtext COLLATE utf8mb4_bin,
  `nursingLicense` longtext COLLATE utf8mb4_bin,
  `shift` longtext COLLATE utf8mb4_bin,
  `shiftTime` longtext COLLATE utf8mb4_bin,
  `shiftStartTime` longtext COLLATE utf8mb4_bin,
  `shiftEndTime` longtext COLLATE utf8mb4_bin,
  `assignedWard` longtext COLLATE utf8mb4_bin,
  `yearsOfExperience` double DEFAULT NULL,
  `qualifications` longtext COLLATE utf8mb4_bin,
  `assistantId` longtext COLLATE utf8mb4_bin,
  `department` longtext COLLATE utf8mb4_bin,
  `supervisor` longtext COLLATE utf8mb4_bin,
  `technicianId` longtext COLLATE utf8mb4_bin,
  `labType` longtext COLLATE utf8mb4_bin,
  `housekeepingStaffId` longtext COLLATE utf8mb4_bin,
  `assignedArea` longtext COLLATE utf8mb4_bin,
  `housekeepingSupervisor` longtext COLLATE utf8mb4_bin,
  `supervisorId` longtext COLLATE utf8mb4_bin,
  `teamSize` double DEFAULT NULL,
  `responsibilities` longtext COLLATE utf8mb4_bin,
  `managerId` longtext COLLATE utf8mb4_bin,
  `employeesUnder` double DEFAULT NULL,
  `budgetResponsibility` longtext COLLATE utf8mb4_bin,
  `billingId` longtext COLLATE utf8mb4_bin,
  `softwareExpertise` longtext COLLATE utf8mb4_bin,
  PRIMARY KEY (`id`),
  KEY `idx_19015382d4fa5129` (`email`(191)),
  KEY `idx_e121ffe8e902749f` (`googleId`(191)),
  KEY `idx_75b9676673a055de` (`isActive`),
  KEY `idx_176d2d8b15512dd4` (`isVerified`),
  KEY `idx_797ee7a9756d82f4` (`lastActiveAt`),
  KEY `idx_a0284a94b200ae05` (`phoneNumber`(191)),
  KEY `idx_1da6f43c70510da8` (`role`(191)),
  KEY `idx_0a30f251cbd7425c` (`uniqueCode`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;
