CREATE TABLE `admin_notification_deliveries` (
  `id` varchar(191) NOT NULL,
  `__v` double DEFAULT NULL,
  `body` longtext DEFAULT NULL,
  `createdAt` datetime(3) DEFAULT NULL,
  `dedupeKey` longtext DEFAULT NULL,
  `error` longtext DEFAULT NULL,
  `mainBackendStatus` double DEFAULT NULL,
  `metadata` longtext DEFAULT NULL CHECK (json_valid(`metadata`)),
  `recipientId` varchar(191) DEFAULT NULL,
  `ruleId` varchar(191) DEFAULT NULL,
  `sentAt` datetime(3) DEFAULT NULL,
  `status` longtext DEFAULT NULL,
  `title` longtext DEFAULT NULL,
  `updatedAt` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_cc35bd28a501e88c` (`dedupeKey`(191)),
  KEY `idx_afeda9ee24f47513` (`recipientId`),
  KEY `idx_4c9eed3979d32843` (`recipientId`,`createdAt`),
  KEY `idx_5a89beb6507c222d` (`ruleId`),
  KEY `idx_f9e04c2ed489350d` (`ruleId`,`recipientId`,`createdAt`),
  KEY `idx_abbccb4418c05119` (`status`(191)),
  KEY `idx_54dcc9df9a11b3b1` (`status`(191),`createdAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;
