CREATE TABLE `calls` (
  `id` varchar(191) NOT NULL,
  `__v` double DEFAULT NULL,
  `acceptedAt` datetime(3) DEFAULT NULL,
  `callerAvatar` longtext DEFAULT NULL,
  `callerId` varchar(191) DEFAULT NULL,
  `callerLocation` longtext DEFAULT NULL,
  `callerLocationData` longtext DEFAULT NULL CHECK (json_valid(`callerLocationData`)),
  `callerName` longtext DEFAULT NULL,
  `callId` longtext DEFAULT NULL,
  `callQuality` longtext DEFAULT NULL,
  `callType` longtext DEFAULT NULL,
  `cancelledAt` datetime(3) DEFAULT NULL,
  `chatId` varchar(191) DEFAULT NULL,
  `createdAt` datetime(3) DEFAULT NULL,
  `duration` double DEFAULT NULL,
  `endedAt` datetime(3) DEFAULT NULL,
  `endedBy` varchar(191) DEFAULT NULL,
  `expiresAt` datetime(3) DEFAULT NULL,
  `initiatorType` longtext DEFAULT NULL,
  `isActive` tinyint(1) DEFAULT NULL,
  `isMuted` tinyint(1) DEFAULT NULL,
  `isOnHold` tinyint(1) DEFAULT NULL,
  `isSpeakerOn` tinyint(1) DEFAULT NULL,
  `paymentAmount` double DEFAULT NULL,
  `paymentStatus` longtext DEFAULT NULL,
  `paymentTransactionId` varchar(191) DEFAULT NULL,
  `receiverAvatar` longtext DEFAULT NULL,
  `receiverId` varchar(191) DEFAULT NULL,
  `receiverLocation` longtext DEFAULT NULL,
  `receiverLocationData` longtext DEFAULT NULL CHECK (json_valid(`receiverLocationData`)),
  `receiverName` longtext DEFAULT NULL,
  `receiverType` longtext DEFAULT NULL,
  `recordingUrl` longtext DEFAULT NULL,
  `rejectedAt` datetime(3) DEFAULT NULL,
  `roomId` longtext DEFAULT NULL,
  `startedAt` datetime(3) DEFAULT NULL,
  `status` longtext DEFAULT NULL,
  `updatedAt` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_a83f9be12de01ecc` (`callId`(191)),
  KEY `idx_728ad3ccd308f9c5` (`callerId`),
  KEY `idx_68ac81cc2c9119c9` (`callerId`,`createdAt`),
  KEY `idx_70e3c548976874a0` (`callerId`,`status`(191),`createdAt`),
  KEY `idx_d6e0971de79c121b` (`chatId`),
  KEY `idx_367c5706027f9ab8` (`createdAt`),
  KEY `idx_981eda66be1f3711` (`receiverId`),
  KEY `idx_2c98da28e558f9fc` (`receiverId`,`createdAt`),
  KEY `idx_16d23569960aab11` (`receiverId`,`status`(191),`createdAt`),
  KEY `idx_c05efabd3813c66d` (`roomId`(191)),
  KEY `idx_abbccb4418c05119` (`status`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;
