CREATE TABLE `chatsessions` (
  `id` varchar(191) NOT NULL,
  `__v` double DEFAULT NULL,
  `acceptedAt` datetime(3) DEFAULT NULL,
  `activeSegmentStartedAt` datetime(3) DEFAULT NULL,
  `amount` double DEFAULT NULL,
  `billedMinutes` double DEFAULT NULL,
  `billedSeconds` double DEFAULT NULL,
  `chatId` varchar(191) DEFAULT NULL,
  `commissionAmount` double DEFAULT NULL,
  `commissionRate` double DEFAULT NULL,
  `counselorEarning` double DEFAULT NULL,
  `counselorId` varchar(191) DEFAULT NULL,
  `createdAt` datetime(3) DEFAULT NULL,
  `earningId` varchar(191) DEFAULT NULL,
  `endedAt` datetime(3) DEFAULT NULL,
  `expiresAt` datetime(3) DEFAULT NULL,
  `lastBilledAt` datetime(3) DEFAULT NULL,
  `metadata` longtext DEFAULT NULL CHECK (json_valid(`metadata`)),
  `paymentStatus` longtext DEFAULT NULL,
  `paymentTransactionId` varchar(191) DEFAULT NULL,
  `rateDurationMinutes` double DEFAULT NULL,
  `ratePerMinute` double DEFAULT NULL,
  `refundReason` longtext DEFAULT NULL,
  `sessionStatus` longtext DEFAULT NULL,
  `sessionType` longtext DEFAULT NULL,
  `startedAt` datetime(3) DEFAULT NULL,
  `updatedAt` datetime(3) DEFAULT NULL,
  `userId` varchar(191) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_d6e0971de79c121b` (`chatId`),
  KEY `idx_d88d957f3c0205e4` (`counselorId`),
  KEY `idx_017d9ff5170a7a1b` (`counselorId`,`sessionStatus`(191),`createdAt`),
  KEY `idx_e1a0f7bca955ecdc` (`expiresAt`),
  KEY `idx_e9c235bf761e20af` (`paymentStatus`(191)),
  KEY `idx_ff6fd02e1c9db805` (`sessionStatus`(191)),
  KEY `idx_91d97889341f2c4c` (`userId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;
