CREATE TABLE `chats` (
  `id` varchar(191) NOT NULL,
  `__v` double DEFAULT NULL,
  `acceptedAt` datetime(3) DEFAULT NULL,
  `amount` double DEFAULT NULL,
  `archivedByCounselor` tinyint(1) DEFAULT NULL,
  `archivedByCounselorAt` datetime(3) DEFAULT NULL,
  `archivedByUser` tinyint(1) DEFAULT NULL,
  `archivedByUserAt` datetime(3) DEFAULT NULL,
  `cancelledAt` datetime(3) DEFAULT NULL,
  `chatId` longtext DEFAULT NULL,
  `closedAt` datetime(3) DEFAULT NULL,
  `counselorId` varchar(191) DEFAULT NULL,
  `deletedByCounselor` tinyint(1) DEFAULT NULL,
  `deletedByUser` tinyint(1) DEFAULT NULL,
  `expiresAt` datetime(3) DEFAULT NULL,
  `isActive` tinyint(1) DEFAULT NULL,
  `lastMessage` longtext DEFAULT NULL,
  `lastMessageAt` datetime(3) DEFAULT NULL,
  `paidSessionId` varchar(191) DEFAULT NULL,
  `paymentStatus` longtext DEFAULT NULL,
  `paymentTransactionId` varchar(191) DEFAULT NULL,
  `rejectedAt` datetime(3) DEFAULT NULL,
  `sessionType` longtext DEFAULT NULL,
  `startedAt` datetime(3) DEFAULT NULL,
  `status` longtext DEFAULT NULL,
  `updatedAt` datetime(3) DEFAULT NULL,
  `userId` varchar(191) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_d5678680368a4e84` (`archivedByCounselor`),
  KEY `idx_6981da248839fe7a` (`archivedByUser`),
  KEY `idx_d6e0971de79c121b` (`chatId`(191)),
  KEY `idx_5e7caa9fd748f7a9` (`deletedByCounselor`),
  KEY `idx_3adc245844ab09ae` (`deletedByUser`),
  KEY `idx_212fab7093cdd16c` (`userId`,`counselorId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;
