CREATE TABLE `counselorearnings` (
  `id` varchar(191) NOT NULL,
  `__v` double DEFAULT NULL,
  `callId` longtext DEFAULT NULL,
  `chatId` varchar(191) DEFAULT NULL,
  `commission` double DEFAULT NULL,
  `counselorId` varchar(191) DEFAULT NULL,
  `createdAt` datetime(3) DEFAULT NULL,
  `earningAmount` double DEFAULT NULL,
  `earningStatus` longtext DEFAULT NULL,
  `metadata` longtext DEFAULT NULL CHECK (json_valid(`metadata`)),
  `paidAt` datetime(3) DEFAULT NULL,
  `payoutStatus` longtext DEFAULT NULL,
  `sessionId` varchar(191) DEFAULT NULL,
  `sessionType` longtext DEFAULT NULL,
  `totalAmount` double DEFAULT NULL,
  `transactionId` varchar(191) DEFAULT NULL,
  `updatedAt` datetime(3) DEFAULT NULL,
  `userId` varchar(191) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_a83f9be12de01ecc` (`callId`(191)),
  KEY `idx_d88d957f3c0205e4` (`counselorId`),
  KEY `idx_86a39bb033a85034` (`earningStatus`(191)),
  KEY `idx_1432f65fb921bc2b` (`payoutStatus`(191)),
  KEY `idx_40c1642a84c9a530` (`sessionId`),
  KEY `idx_2c6c1a05438be45c` (`transactionId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;
