CREATE TABLE `notificationrules` (
  `id` varchar(191) NOT NULL,
  `__v` double DEFAULT NULL,
  `actionUrl` longtext DEFAULT NULL,
  `audience` longtext DEFAULT NULL,
  `body` longtext DEFAULT NULL,
  `condition` longtext DEFAULT NULL,
  `createdAt` datetime(3) DEFAULT NULL,
  `createdBy` longtext DEFAULT NULL CHECK (json_valid(`createdBy`)),
  `data` longtext DEFAULT NULL CHECK (json_valid(`data`)),
  `lastProcessedAt` datetime(3) DEFAULT NULL,
  `notificationType` longtext DEFAULT NULL,
  `scheduledAt` datetime(3) DEFAULT NULL,
  `selectedCounsellorIds` longtext DEFAULT NULL CHECK (json_valid(`selectedCounsellorIds`)),
  `selectedUserIds` longtext DEFAULT NULL CHECK (json_valid(`selectedUserIds`)),
  `sendImmediately` tinyint(1) DEFAULT NULL,
  `specialization` longtext DEFAULT NULL,
  `status` longtext DEFAULT NULL,
  `timezone` longtext DEFAULT NULL,
  `title` longtext DEFAULT NULL,
  `updatedAt` datetime(3) DEFAULT NULL,
  `updatedBy` longtext DEFAULT NULL CHECK (json_valid(`updatedBy`)),
  PRIMARY KEY (`id`),
  KEY `idx_a3059620bfdd2526` (`audience`(191)),
  KEY `idx_1e815076a0e484c2` (`condition`(191)),
  KEY `idx_2a135b96c342cdbc` (`lastProcessedAt`),
  KEY `idx_eae389a133e6264c` (`notificationType`(191)),
  KEY `idx_dda8bcf0a12129ca` (`notificationType`(191),`specialization`(191)),
  KEY `idx_b36131554c3bae46` (`scheduledAt`),
  KEY `idx_abbccb4418c05119` (`status`(191)),
  KEY `idx_3ec726712fd2bf5b` (`status`(191),`condition`(191),`audience`(191)),
  KEY `idx_5fe964e5cb716b99` (`status`(191),`condition`(191),`scheduledAt`,`lastProcessedAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;
