CREATE TABLE `payouts` (
  `id` varchar(191) NOT NULL,
  `__v` double DEFAULT NULL,
  `amount` double DEFAULT NULL,
  `approvedAt` datetime(3) DEFAULT NULL,
  `approvedBy` varchar(191) DEFAULT NULL,
  `bankDetails` longtext DEFAULT NULL CHECK (json_valid(`bankDetails`)),
  `completedAt` datetime(3) DEFAULT NULL,
  `counselorEmail` longtext DEFAULT NULL,
  `counselorId` varchar(191) DEFAULT NULL,
  `counselorName` longtext DEFAULT NULL,
  `createdAt` datetime(3) DEFAULT NULL,
  `currency` longtext DEFAULT NULL,
  `failureReason` longtext DEFAULT NULL,
  `metadata` longtext DEFAULT NULL CHECK (json_valid(`metadata`)),
  `netAmount` double DEFAULT NULL,
  `notes` longtext DEFAULT NULL,
  `paymentMethod` longtext DEFAULT NULL,
  `payoutId` longtext DEFAULT NULL,
  `period` longtext DEFAULT NULL CHECK (json_valid(`period`)),
  `processedAt` datetime(3) DEFAULT NULL,
  `processedBy` varchar(191) DEFAULT NULL,
  `status` longtext DEFAULT NULL,
  `taxAmount` double DEFAULT NULL,
  `taxDocument` longtext DEFAULT NULL,
  `transactionReference` longtext DEFAULT NULL,
  `updatedAt` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_d88d957f3c0205e4` (`counselorId`),
  KEY `idx_937c959d4c755289` (`counselorId`,`createdAt`),
  KEY `idx_367c5706027f9ab8` (`createdAt`),
  KEY `idx_9d1551d9b168ec62` (`payoutId`(191)),
  KEY `idx_abbccb4418c05119` (`status`(191)),
  KEY `idx_54dcc9df9a11b3b1` (`status`(191),`createdAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;
