CREATE TABLE `prescriptions` (
  `id` varchar(191) NOT NULL,
  `__v` double DEFAULT NULL,
  `chatId` varchar(191) DEFAULT NULL,
  `createdAt` datetime(3) DEFAULT NULL,
  `festivalTheme` longtext DEFAULT NULL,
  `identityVerification` longtext DEFAULT NULL CHECK (json_valid(`identityVerification`)),
  `instructions` longtext DEFAULT NULL,
  `issuedAt` datetime(3) DEFAULT NULL,
  `medicines` longtext DEFAULT NULL CHECK (json_valid(`medicines`)),
  `patientId` varchar(191) DEFAULT NULL,
  `patientPhoto` longtext DEFAULT NULL CHECK (json_valid(`patientPhoto`)),
  `patientSnapshot` longtext DEFAULT NULL CHECK (json_valid(`patientSnapshot`)),
  `pdf` longtext DEFAULT NULL CHECK (json_valid(`pdf`)),
  `problem` longtext DEFAULT NULL,
  `psychiatristId` varchar(191) DEFAULT NULL,
  `psychiatristSnapshot` longtext DEFAULT NULL CHECK (json_valid(`psychiatristSnapshot`)),
  `updatedAt` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_d6e0971de79c121b` (`chatId`),
  KEY `idx_e8ceafd5b761bbb0` (`issuedAt`),
  KEY `idx_d1b6704a2a3c71e5` (`patientId`),
  KEY `idx_db217aed9247ecec` (`patientId`,`issuedAt`),
  KEY `idx_3c63cefb5165bed8` (`psychiatristId`),
  KEY `idx_e61cc348cc86d218` (`psychiatristId`,`issuedAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;
