CREATE TABLE `ratings` (
  `id` varchar(191) NOT NULL,
  `__v` double DEFAULT NULL,
  `chatId` longtext DEFAULT NULL,
  `comment` longtext DEFAULT NULL,
  `counselor` varchar(191) DEFAULT NULL,
  `counselorId` varchar(191) DEFAULT NULL,
  `createdAt` datetime(3) DEFAULT NULL,
  `rating` double DEFAULT NULL,
  `review` longtext DEFAULT NULL,
  `sessionId` longtext DEFAULT NULL,
  `stars` double DEFAULT NULL,
  `status` longtext DEFAULT NULL,
  `updatedAt` datetime(3) DEFAULT NULL,
  `user` varchar(191) DEFAULT NULL,
  `userId` varchar(191) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_d88d957f3c0205e4` (`counselorId`),
  KEY `idx_66b1ac224742015c` (`counselor`),
  KEY `idx_abbccb4418c05119` (`status`(191)),
  KEY `idx_91d97889341f2c4c` (`userId`),
  KEY `idx_74e0c72354af70bf` (`userId`,`chatId`(191)),
  KEY `idx_79b0aa0042b3c056` (`user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;
