CREATE TABLE `supporttickets` (
  `id` varchar(191) NOT NULL,
  `__v` double DEFAULT NULL,
  `assignedTo` longtext DEFAULT NULL,
  `callDispute` longtext DEFAULT NULL CHECK (json_valid(`callDispute`)),
  `createdAt` datetime(3) DEFAULT NULL,
  `lastMessageAt` datetime(3) DEFAULT NULL,
  `messages` longtext DEFAULT NULL CHECK (json_valid(`messages`)),
  `priority` longtext DEFAULT NULL,
  `requesterEmail` longtext DEFAULT NULL,
  `requesterName` longtext DEFAULT NULL,
  `resolvedAt` datetime(3) DEFAULT NULL,
  `source` longtext DEFAULT NULL,
  `status` longtext DEFAULT NULL,
  `subject` longtext DEFAULT NULL,
  `ticketNumber` longtext DEFAULT NULL,
  `unreadByAdmin` tinyint(1) DEFAULT NULL,
  `updatedAt` datetime(3) DEFAULT NULL,
  `userId` varchar(191) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_f4f6e0c43fc8a420` (`lastMessageAt`),
  KEY `idx_19f840cf99ce2ad7` (`priority`(191)),
  KEY `idx_2040d747932846ad` (`requesterEmail`(191)),
  KEY `idx_abbccb4418c05119` (`status`(191)),
  KEY `idx_3513e07aaafb9e5e` (`status`(191),`lastMessageAt`),
  KEY `idx_6f635359d3dd6d3a` (`ticketNumber`(191)),
  KEY `idx_b4a51be702a4f052` (`unreadByAdmin`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;
