CREATE TABLE `transactions` (
  `id` varchar(191) NOT NULL,
  `__v` double DEFAULT NULL,
  `amount` double DEFAULT NULL,
  `chatId` varchar(191) DEFAULT NULL,
  `counselorEarnings` double DEFAULT NULL,
  `counselorId` varchar(191) DEFAULT NULL,
  `createdAt` datetime(3) DEFAULT NULL,
  `currency` longtext DEFAULT NULL,
  `description` longtext DEFAULT NULL,
  `metadata` longtext DEFAULT NULL CHECK (json_valid(`metadata`)),
  `paymentMethod` longtext DEFAULT NULL,
  `platformFee` double DEFAULT NULL,
  `razorpayOrderId` longtext DEFAULT NULL,
  `razorpayPaymentId` longtext DEFAULT NULL,
  `razorpaySignature` longtext DEFAULT NULL,
  `relatedTransactionId` varchar(191) DEFAULT NULL,
  `sessionId` varchar(191) DEFAULT NULL,
  `status` longtext DEFAULT NULL,
  `transactionId` longtext DEFAULT NULL,
  `type` longtext DEFAULT NULL,
  `updatedAt` datetime(3) DEFAULT NULL,
  `userId` varchar(191) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_0a38c775c0eee44a` (`razorpayOrderId`(191)),
  KEY `idx_3ba12a9f2f2cacc6` (`razorpayPaymentId`(191)),
  KEY `idx_2c6c1a05438be45c` (`transactionId`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;
