CREATE TABLE `users` (
  `id` varchar(191) NOT NULL,
  `__v` double DEFAULT NULL,
  `aboutMe` longtext DEFAULT NULL,
  `activeClients` double DEFAULT NULL,
  `activeWalletRefundRequest` tinyint(1) DEFAULT NULL,
  `address` longtext DEFAULT NULL CHECK (json_valid(`address`)),
  `age` double DEFAULT NULL,
  `anonymous` longtext DEFAULT NULL,
  `authProvider` longtext DEFAULT NULL,
  `availability` longtext DEFAULT NULL,
  `bio` longtext DEFAULT NULL,
  `bloodGroup` longtext DEFAULT NULL,
  `certifications` longtext DEFAULT NULL CHECK (json_valid(`certifications`)),
  `chatContext` longtext DEFAULT NULL CHECK (json_valid(`chatContext`)),
  `chatPermission` longtext DEFAULT NULL CHECK (json_valid(`chatPermission`)),
  `consultationMode` longtext DEFAULT NULL CHECK (json_valid(`consultationMode`)),
  `createdAt` datetime(3) DEFAULT NULL,
  `dateOfBirth` datetime(3) DEFAULT NULL,
  `devicePlatform` longtext DEFAULT NULL,
  `education` longtext DEFAULT NULL,
  `email` longtext DEFAULT NULL,
  `emailOTP` longtext DEFAULT NULL CHECK (json_valid(`emailOTP`)),
  `emergencyContact` longtext DEFAULT NULL CHECK (json_valid(`emergencyContact`)),
  `experience` double DEFAULT NULL,
  `fcmToken` longtext DEFAULT NULL,
  `fullName` longtext DEFAULT NULL,
  `gender` longtext DEFAULT NULL,
  `googleEmail` longtext DEFAULT NULL,
  `googleId` longtext DEFAULT NULL,
  `hourlyRate` double DEFAULT NULL,
  `instantPayoutCount` double DEFAULT NULL,
  `insuranceInfo` longtext DEFAULT NULL CHECK (json_valid(`insuranceInfo`)),
  `isActive` tinyint(1) DEFAULT NULL,
  `isEmailVerified` tinyint(1) DEFAULT NULL,
  `isOnline` tinyint(1) DEFAULT NULL,
  `isPhoneVerified` tinyint(1) DEFAULT NULL,
  `isVerified` tinyint(1) DEFAULT NULL,
  `languages` longtext DEFAULT NULL CHECK (json_valid(`languages`)),
  `lastActiveAt` datetime(3) DEFAULT NULL,
  `lastSeen` datetime(3) DEFAULT NULL,
  `location` longtext DEFAULT NULL,
  `locationConsent` tinyint(1) DEFAULT NULL,
  `locationData` longtext DEFAULT NULL CHECK (json_valid(`locationData`)),
  `medicalInfo` longtext DEFAULT NULL CHECK (json_valid(`medicalInfo`)),
  `password` longtext DEFAULT NULL,
  `payoutAccount` longtext DEFAULT NULL CHECK (json_valid(`payoutAccount`)),
  `phone` longtext DEFAULT NULL,
  `phoneCountryCode` longtext DEFAULT NULL,
  `phoneNumber` longtext DEFAULT NULL,
  `phoneOTP` longtext DEFAULT NULL CHECK (json_valid(`phoneOTP`)),
  `prescriptionSeal` longtext DEFAULT NULL CHECK (json_valid(`prescriptionSeal`)),
  `prescriptionSignature` longtext DEFAULT NULL CHECK (json_valid(`prescriptionSignature`)),
  `profileCompleted` tinyint(1) DEFAULT NULL,
  `profilePhoto` longtext DEFAULT NULL CHECK (json_valid(`profilePhoto`)),
  `profilePhotoPublicId` longtext DEFAULT NULL,
  `profilePicture` longtext DEFAULT NULL,
  `qualification` longtext DEFAULT NULL,
  `rating` double DEFAULT NULL,
  `ratingCount` double DEFAULT NULL,
  `refreshToken` longtext DEFAULT NULL,
  `role` longtext DEFAULT NULL,
  `sessionId` longtext DEFAULT NULL,
  `sessionsDone` double DEFAULT NULL,
  `specialization` longtext DEFAULT NULL CHECK (json_valid(`specialization`)),
  `totalSessions` double DEFAULT NULL,
  `uniqueCode` longtext DEFAULT NULL,
  `updatedAt` datetime(3) DEFAULT NULL,
  `walletAdjustmentIds` longtext DEFAULT NULL CHECK (json_valid(`walletAdjustmentIds`)),
  `walletBalance` double DEFAULT NULL,
  `walletCreditPaymentIds` longtext DEFAULT NULL CHECK (json_valid(`walletCreditPaymentIds`)),
  PRIMARY KEY (`id`),
  KEY `idx_19015382d4fa5129` (`email`(191)),
  KEY `idx_e121ffe8e902749f` (`googleId`(191)),
  KEY `idx_75b9676673a055de` (`isActive`),
  KEY `idx_176d2d8b15512dd4` (`isVerified`),
  KEY `idx_797ee7a9756d82f4` (`lastActiveAt`),
  KEY `idx_a0284a94b200ae05` (`phoneNumber`(191)),
  KEY `idx_1da6f43c70510da8` (`role`(191)),
  KEY `idx_0a30f251cbd7425c` (`uniqueCode`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;
