CREATE TABLE `appointments` (
  `id` varchar(191) COLLATE utf8mb4_bin NOT NULL,
  `patient` varchar(191) COLLATE utf8mb4_bin DEFAULT NULL,
  `counselor` varchar(191) COLLATE utf8mb4_bin DEFAULT NULL,
  `date` datetime(3) DEFAULT NULL,
  `notes` longtext COLLATE utf8mb4_bin,
  `status` longtext COLLATE utf8mb4_bin,
  `createdAt` datetime(3) DEFAULT NULL,
  `updatedAt` datetime(3) DEFAULT NULL,
  `__v` double DEFAULT NULL,
  `clinic_id` varchar(191) COLLATE utf8mb4_bin DEFAULT NULL,
  `appointment_date` longtext COLLATE utf8mb4_bin,
  `appointment_time` longtext COLLATE utf8mb4_bin,
  `token_number` double DEFAULT NULL,
  `slot_key` longtext COLLATE utf8mb4_bin,
  `booking_source` longtext COLLATE utf8mb4_bin,
  `symptoms` longtext COLLATE utf8mb4_bin,
  `diagnosis` longtext COLLATE utf8mb4_bin,
  `advice` longtext COLLATE utf8mb4_bin,
  `patient_location` longtext COLLATE utf8mb4_bin,
  `consultation_mode` longtext COLLATE utf8mb4_bin,
  `checked_in_at` datetime(3) DEFAULT NULL,
  `vitals` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_5e1500f0c396dd66` (`slot_key`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;
