CREATE TABLE `users` (
  `id` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `fullName` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `email` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `anonymous` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `phoneNumber` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `phoneCountryCode` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `password` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `googleEmail` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `authProvider` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `sessionId` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `walletCreditPaymentIds` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `age` double DEFAULT NULL,
  `gender` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `role` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `profileCompleted` tinyint(1) DEFAULT NULL,
  `chatContext` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `isEmailVerified` tinyint(1) DEFAULT NULL,
  `isPhoneVerified` tinyint(1) DEFAULT NULL,
  `dateOfBirth` datetime(3) DEFAULT NULL,
  `bloodGroup` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `address` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `emergencyContact` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `medicalInfo` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `insuranceInfo` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `specialization` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `consultationMode` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `languages` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `education` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `rating` double DEFAULT NULL,
  `ratingCount` double DEFAULT NULL,
  `totalSessions` double DEFAULT NULL,
  `activeClients` double DEFAULT NULL,
  `profilePhotoPublicId` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `chatPermission` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `isActive` tinyint(1) DEFAULT NULL,
  `isVerified` tinyint(1) DEFAULT NULL,
  `isOnline` tinyint(1) DEFAULT NULL,
  `lastSeen` datetime(3) DEFAULT NULL,
  `walletBalance` double DEFAULT NULL,
  `devicePlatform` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `instantPayoutCount` double DEFAULT NULL,
  `payoutAccount` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `locationConsent` tinyint(1) DEFAULT NULL,
  `locationData` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `certifications` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `createdAt` datetime(3) DEFAULT NULL,
  `updatedAt` datetime(3) DEFAULT NULL,
  `__v` double DEFAULT NULL,
  `googleId` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `activeWalletRefundRequest` tinyint(1) DEFAULT NULL,
  `prescriptionSeal` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `prescriptionSignature` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `lastActiveAt` datetime(3) DEFAULT NULL,
  `fcmToken` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `walletAdjustmentIds` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `phone` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `profilePicture` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `hourlyRate` double DEFAULT NULL,
  `sessionsDone` double DEFAULT NULL,
  `bio` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `availability` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `accountType` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `doctorQrCode` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `staffId` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `nursingLicense` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `shift` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `shiftTime` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `shiftStartTime` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `shiftEndTime` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `assignedWard` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `yearsOfExperience` double DEFAULT NULL,
  `qualifications` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `assistantId` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `department` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `supervisor` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `technicianId` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `labType` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `housekeepingStaffId` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `assignedArea` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `housekeepingSupervisor` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `supervisorId` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `teamSize` double DEFAULT NULL,
  `responsibilities` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `managerId` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `employeesUnder` double DEFAULT NULL,
  `budgetResponsibility` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `billingId` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `softwareExpertise` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `emailOTP` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `phoneOTP` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `qualification` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `experience` double DEFAULT NULL,
  `location` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `aboutMe` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `uniqueCode` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `profilePhoto` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `refreshToken` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `assignedDoctor` varchar(191) COLLATE utf8mb4_bin DEFAULT NULL,
  `staffCertifications` longtext COLLATE utf8mb4_bin,
  PRIMARY KEY (`id`),
  KEY `idx_19015382d4fa5129` (`email`(191)),
  KEY `idx_e121ffe8e902749f` (`googleId`(191)),
  KEY `idx_75b9676673a055de` (`isActive`),
  KEY `idx_176d2d8b15512dd4` (`isVerified`),
  KEY `idx_797ee7a9756d82f4` (`lastActiveAt`),
  KEY `idx_a0284a94b200ae05` (`phoneNumber`(191)),
  KEY `idx_1da6f43c70510da8` (`role`(191)),
  KEY `idx_0a30f251cbd7425c` (`uniqueCode`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;
